#!/bin/bash
# Update watermarks in sequence diagram documentation

set -e

echo "🏷️ Updating sequence diagram watermarks..."

# Get current version and date
VERSION=$(cat version.txt | tr -d '\n')
CURRENT_DATE=$(date +"%Y-%m-%d")
CURRENT_DATE_FORMATTED=$(date +"%B %-d, %Y")

echo "📋 Using version: v$VERSION"
echo "📅 Using date: $CURRENT_DATE_FORMATTED"

# Update or add version in all MDX files
for file in docs/content/developer-guide/Diagrams/Sequence-Diagrams/*.mdx; do
    if [ -f "$file" ]; then
        echo "Processing: $(basename "$file")"
        
        # Check if version line already exists
        if grep -q "^Version: v" "$file"; then
            # Update existing version
            sed -i.bak "s/^Version: v[0-9.]*/Version: v$VERSION/" "$file"
        else
            # Add version before the last line if it doesn't exist
            # Find the last paragraph and add version after it
            if grep -q "This comprehensive.*" "$file"; then
                # Add version after the "This comprehensive..." paragraph
                sed -i.bak "/This comprehensive.*\./a\\
\\
Version: v$VERSION" "$file"
            else
                # Fallback: add at the end of the file
                echo "" >> "$file"
                echo "Version: v$VERSION" >> "$file"
            fi
        fi
        
        # Update date in "Last updated on..." if it exists
        sed -i.bak "s/Last updated on [A-Za-z0-9, ]*/Last updated on $CURRENT_DATE_FORMATTED/g" "$file"
    fi
done

# Remove backup files
find docs/content/developer-guide/Diagrams/Sequence-Diagrams/ -name "*.bak" -delete

# Update marketplace package
echo "📦 Updating marketplace package..."
MARKETPLACE_DIR="docs/marketplace/ark-sequence-v$VERSION"

# Create marketplace directory if it doesn't exist
mkdir -p "$MARKETPLACE_DIR"

# Copy updated diagrams to marketplace
cp docs/content/developer-guide/Diagrams/Sequence-Diagrams/*.mdx "$MARKETPLACE_DIR/"

# Update marketplace README
cat > "$MARKETPLACE_DIR/README.md" << EOF
# ARK Sequence Diagrams v$VERSION

**Generated:** $CURRENT_DATE_FORMATTED  
**ARK Version:** v$VERSION  
**Status:** ✅ Auto-generated and maintained

## 📋 Available Diagrams

This marketplace package contains comprehensive sequence diagrams for the ARK platform, isolated to avoid context saturation in agent workflows.

### Core Execution Flows
- [\`agent-execution-flow.mdx\`](./agent-execution-flow.mdx) - Complete agent execution lifecycle
- [\`basic-query-execution.mdx\`](./basic-query-execution.mdx) - Basic query processing flow
- [\`external-execution-engine-langchain.mdx\`](./external-execution-engine-langchain.mdx) - Langchain integration

### Platform Components  
- [\`crd-lifecycle-management.mdx\`](./crd-lifecycle-management.mdx) - Kubernetes CRD lifecycle
- [\`event-recording-tracking.mdx\`](./event-recording-tracking.mdx) - Event system monitoring
- [\`langfuse-service.mdx\`](./langfuse-service.mdx) - Langfuse integration patterns

### Tool & Service Integration
- [\`mcpserver-to-tools.mdx\`](./mcpserver-to-tools.mdx) - MCP Server tool connectivity
- [\`memory-service.mdx\`](./memory-service.mdx) - Memory service operations
- [\`tool-execution.mdx\`](./tool-execution.mdx) - Tool execution workflows

### Team Management
- [\`team-round-robin-strategy.mdx\`](./team-round-robin-strategy.mdx) - Team routing strategies

## 🔄 Auto-Generation

This package is automatically updated via:
- **GitHub Actions**: Triggers on code changes
- **Version Tracking**: Synced with main ARK version
- **Watermark System**: Dynamic version and date stamps

## 🎯 Usage

**For Agents**: Reference specific diagrams without loading the entire codebase context
**For Documentation**: Stable, versioned diagram references
**For Development**: Up-to-date architectural understanding

## 📁 Structure

\`\`\`
ark-sequence-v$VERSION/
├── README.md                           # This file
├── agent-execution-flow.mdx            # Agent lifecycle
├── basic-query-execution.mdx           # Query processing
├── crd-lifecycle-management.mdx        # K8s CRD management
├── event-recording-tracking.mdx        # Event monitoring
├── external-execution-engine-langchain.mdx # Langchain flows
├── langfuse-service.mdx                # Langfuse integration
├── mcpserver-to-tools.mdx              # MCP connectivity
├── memory-service.mdx                  # Memory operations
├── team-round-robin-strategy.mdx       # Team strategies
└── tool-execution.mdx                  # Tool workflows
\`\`\`

---
*Auto-generated by ARK Sequence Diagram System*
EOF

echo "✅ Updated watermarks in sequence diagrams:"
find docs/content/developer-guide/Diagrams/Sequence-Diagrams/ -name "*.mdx" -exec basename {} \; | sed 's/^/  - /'

echo "📦 Updated marketplace package:"
echo "  - Location: $MARKETPLACE_DIR"
echo "  - Files: $(ls -1 "$MARKETPLACE_DIR" | wc -l | tr -d ' ') files"

echo ""
echo "💡 Tip: Run 'git diff' to see the changes"
